# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' } { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel' city: cities.first)
Specialty.create(name: 'Allergy')
Specialty.create(name: 'Anesthesia')
Specialty.create(name: 'Associate Degree and Diploma Nurses')
Specialty.create(name: 'Athletic Trainer')
Specialty.create(name: 'Baccalaureate Prepared Nurses')
Specialty.create(name: 'Bioengineering/Biomedical Engineering')
Specialty.create(name: 'Cardiac Surgery')
Specialty.create(name: 'Cardiology')
Specialty.create(name: 'Chiropractics ')
Specialty.create(name: 'Counseling')
Specialty.create(name: 'Dental Assistant')
Specialty.create(name: 'Dental Hygienist')
Specialty.create(name: 'Dental Lab Technician')
Specialty.create(name: 'Dentist')
Specialty.create(name: 'Dermatology')
Specialty.create(name: 'Doctoral Prepared Nurses')
Specialty.create(name: 'Ear / Nose / Throat')
Specialty.create(name: 'Emergency Medicine')
Specialty.create(name: 'Endocrinology')
Specialty.create(name: 'Environmental Health')
Specialty.create(name: 'Epidemology')
Specialty.create(name: 'Family Medicine')
Specialty.create(name: 'Gastroeterology')
Specialty.create(name: 'General Surgery')
Specialty.create(name: 'Health Education')
Specialty.create(name: 'Healthcare Administration')
Specialty.create(name: 'Hematology')
Specialty.create(name: 'Infectious Disease')
Specialty.create(name: 'Internal Medicine')
Specialty.create(name: 'International Health')
Specialty.create(name: 'Lab Medicine')
Specialty.create(name: 'Laboratory Technician')
Specialty.create(name: 'Masters Prepared Nurses')
Specialty.create(name: 'Mental Health')
Specialty.create(name: 'Midwife')
Specialty.create(name: 'Nephrology')
Specialty.create(name: 'Neurology')
Specialty.create(name: 'Non-Medical')
Specialty.create(name: 'Nutrition')
Specialty.create(name: 'Obstetrics / Gynecology')
Specialty.create(name: 'Occupational Therapy')
Specialty.create(name: 'Oncology')
Specialty.create(name: 'Ophthalmology')
Specialty.create(name: 'Optometry')
Specialty.create(name: 'Oral Surgeon')
Specialty.create(name: 'Orthopaedic Surgery')
Specialty.create(name: 'Osteopathic')
Specialty.create(name: 'Other (Medical)')
Specialty.create(name: 'Other (Surgical)')
Specialty.create(name: 'Paramedic/Aviation Medicine')
Specialty.create(name: 'Pediatrics')
Specialty.create(name: 'Pharmacy')
Specialty.create(name: 'Physical Medicine and Rehabilitation')
Specialty.create(name: 'Physical Therapy')
Specialty.create(name: 'Physician Assistant')
Specialty.create(name: 'Plastic Surgery')
Specialty.create(name: 'Public Health')
Specialty.create(name: 'Pulmonology')
Specialty.create(name: 'Radiology')
Specialty.create(name: 'Radiology Technician')
Specialty.create(name: 'Research')
Specialty.create(name: 'Rheumatology')
Specialty.create(name: 'Social Services')
Specialty.create(name: 'Speech Pathology')
Specialty.create(name: 'Water & Sanitation')
Country.create(name: 'Afghanistan', alpha_2: 'af', alpha_3: 'afg')
Country.create(name: 'Aland Islands', alpha_2: 'ax', alpha_3: 'ala')
Country.create(name: 'Albania', alpha_2: 'al', alpha_3: 'alb')
Country.create(name: 'Algeria', alpha_2: 'dz', alpha_3: 'dza')
Country.create(name: 'American Samoa', alpha_2: 'as', alpha_3: 'asm')
Country.create(name: 'Andorra', alpha_2: 'ad', alpha_3: 'and')
Country.create(name: 'Angola', alpha_2: 'ao', alpha_3: 'ago')
Country.create(name: 'Anguilla', alpha_2: 'ai', alpha_3: 'aia')
Country.create(name: 'Antarctica',  alpha_2: 'aq', alpha_3: '')
Country.create(name: 'Antigua and Barbuda', alpha_2: 'ag', alpha_3: 'atg')
Country.create(name: 'Argentina', alpha_2: 'ar', alpha_3: 'arg')
Country.create(name: 'Armenia', alpha_2: 'am', alpha_3: 'arm')
Country.create(name: 'Aruba', alpha_2: 'aw', alpha_3: 'abw')
Country.create(name: 'Australia', alpha_2: 'au', alpha_3: 'aus')
Country.create(name: 'Austria', alpha_2: 'at', alpha_3: 'aut')
Country.create(name: 'Azerbaijan', alpha_2: 'az', alpha_3: 'aze')
Country.create(name: 'Bahamas', alpha_2: 'bs', alpha_3: 'bhs')
Country.create(name: 'Bahrain', alpha_2: 'bh', alpha_3: 'bhr')
Country.create(name: 'Bangladesh', alpha_2: 'bd', alpha_3: 'bgd')
Country.create(name: 'Barbados', alpha_2: 'bb', alpha_3: 'brb')
Country.create(name: 'Belarus', alpha_2: 'by', alpha_3: 'blr')
Country.create(name: 'Belgium', alpha_2: 'be', alpha_3: 'bel')
Country.create(name: 'Belize', alpha_2: 'bz', alpha_3: 'blz')
Country.create(name: 'Benin', alpha_2: 'bj', alpha_3: 'ben')
Country.create(name: 'Bermuda', alpha_2: 'bm', alpha_3: 'bmu')
Country.create(name: 'Bhutan', alpha_2: 'bt', alpha_3: 'btn')
Country.create(name: 'Bolivia, Plurinational State of', alpha_2: 'bo', alpha_3: 'bol')
Country.create(name: 'Bonaire, Sint Eustatius and Saba', alpha_2: 'bq', alpha_3: 'bes')
Country.create(name: 'Bosnia and Herzegovina', alpha_2: 'ba', alpha_3: 'bih')
Country.create(name: 'Botswana', alpha_2: 'bw', alpha_3: 'bwa')
Country.create(name: 'Bouvet Island',  alpha_2: 'bv',  alpha_3: '')
Country.create(name: 'Brazil', alpha_2: 'br', alpha_3: 'bra')
Country.create(name: 'British Indian Ocean Territory',  alpha_2: 'io',  alpha_3: '')
Country.create(name: 'Brunei Darussalam', alpha_2: 'bn', alpha_3: 'brn')
Country.create(name: 'Bulgaria', alpha_2: 'bg', alpha_3: 'bgr')
Country.create(name: 'Burkina Faso', alpha_2: 'bf', alpha_3: 'bfa')
Country.create(name: 'Burundi', alpha_2: 'bi', alpha_3: 'bdi')
Country.create(name: 'Cambodia', alpha_2: 'kh', alpha_3: 'khm')
Country.create(name: 'Cameroon', alpha_2: 'cm', alpha_3: 'cmr')
Country.create(name: 'Canada', alpha_2: 'ca', alpha_3: 'can')
Country.create(name: 'Cape Verde', alpha_2: 'cv', alpha_3: 'cpv')
Country.create(name: 'Cayman Islands', alpha_2: 'ky', alpha_3: 'cym')
Country.create(name: 'Central African Republic', alpha_2: 'cf', alpha_3: 'caf')
Country.create(name: 'Chad', alpha_2: 'td', alpha_3: 'tcd')
Country.create(name: 'Chile', alpha_2: 'cl', alpha_3: 'chl')
Country.create(name: 'China', alpha_2: 'cn', alpha_3: 'chn')
Country.create(name: 'Christmas Island',  alpha_2: 'cx',  alpha_3: '')
Country.create(name: 'Cocos (Keeling) Islands',  alpha_2: 'cc',  alpha_3: '')
Country.create(name: 'Colombia', alpha_2: 'co', alpha_3: 'col')
Country.create(name: 'Comoros', alpha_2: 'km', alpha_3: 'com')
Country.create(name: 'Congo', alpha_2: 'cg', alpha_3: 'cog')
Country.create(name: 'Congo, The Democratic Republic of the', alpha_2: 'cd', alpha_3: 'cod')
Country.create(name: 'Cook Islands', alpha_2: 'ck', alpha_3: 'cok')
Country.create(name: 'Costa Rica', alpha_2: 'cr', alpha_3: 'cri')
Country.create(name: "Cote d'Ivoire", alpha_2: 'ci', alpha_3: 'civ')
Country.create(name: 'Croatia', alpha_2: 'hr', alpha_3: 'hrv')
Country.create(name: 'Cuba', alpha_2: 'cu', alpha_3: 'cub')
Country.create(name: 'Curacao', alpha_2: 'cw', alpha_3: 'cuw')
Country.create(name: 'Cyprus', alpha_2: 'cy', alpha_3: 'cyp')
Country.create(name: 'Czech Republic', alpha_2: 'cz', alpha_3: 'cze')
Country.create(name: 'Denmark', alpha_2: 'dk', alpha_3: 'dnk')
Country.create(name: 'Djibouti', alpha_2: 'dj', alpha_3: 'dji')
Country.create(name: 'Dominica', alpha_2: 'dm', alpha_3: 'dma')
Country.create(name: 'Dominican Republic', alpha_2: 'do', alpha_3: 'dom')
Country.create(name: 'Ecuador', alpha_2: 'ec', alpha_3: 'ecu')
Country.create(name: 'Egypt', alpha_2: 'eg', alpha_3: 'egy')
Country.create(name: 'El Salvador', alpha_2: 'sv', alpha_3: 'slv')
Country.create(name: 'Equatorial Guinea', alpha_2: 'gq', alpha_3: 'gnq')
Country.create(name: 'Eritrea', alpha_2: 'er', alpha_3: 'eri')
Country.create(name: 'Estonia', alpha_2: 'ee', alpha_3: 'est')
Country.create(name: 'Ethiopia', alpha_2: 'et', alpha_3: 'eth')
Country.create(name: 'Falkland Islands (Malvinas)', alpha_2: 'fk', alpha_3: 'flk')
Country.create(name: 'Faroe Islands', alpha_2: 'fo', alpha_3: 'fro')
Country.create(name: 'Fiji', alpha_2: 'fj', alpha_3: 'fji')
Country.create(name: 'Finland', alpha_2: 'fi', alpha_3: 'fin')
Country.create(name: 'France', alpha_2: 'fr', alpha_3: 'fra')
Country.create(name: 'French Guiana', alpha_2: 'gf', alpha_3: 'guf')
Country.create(name: 'French Polynesia', alpha_2: 'pf', alpha_3: 'pyf')
Country.create(name: 'French Southern Territories',  alpha_2: 'tf',  alpha_3: '')
Country.create(name: 'Gabon', alpha_2: 'ga', alpha_3: 'gab')
Country.create(name: 'Gambia', alpha_2: 'gm', alpha_3: 'gmb')
Country.create(name: 'Georgia', alpha_2: 'ge', alpha_3: 'geo')
Country.create(name: 'Germany', alpha_2: 'de', alpha_3: 'deu')
Country.create(name: 'Ghana', alpha_2: 'gh', alpha_3: 'gha')
Country.create(name: 'Gibraltar', alpha_2: 'gi', alpha_3: 'gib')
Country.create(name: 'Greece', alpha_2: 'gr', alpha_3: 'grc')
Country.create(name: 'Greenland', alpha_2: 'gl', alpha_3: 'grl')
Country.create(name: 'Grenada', alpha_2: 'gd', alpha_3: 'grd')
Country.create(name: 'Guadeloupe', alpha_2: 'gp', alpha_3: 'glp')
Country.create(name: 'Guam', alpha_2: 'gu', alpha_3: 'gum')
Country.create(name: 'Guatemala', alpha_2: 'gt', alpha_3: 'gtm')
Country.create(name: 'Guernsey', alpha_2: 'gg', alpha_3: 'ggy')
Country.create(name: 'Guinea', alpha_2: 'gn', alpha_3: 'gin')
Country.create(name: 'Guinea-Bissau', alpha_2: 'gw', alpha_3: 'gnb')
Country.create(name: 'Guyana', alpha_2: 'gy', alpha_3: 'guy')
Country.create(name: 'Haiti', alpha_2: 'ht', alpha_3: 'hti')
Country.create(name: 'Heard Island and McDonald Islands',  alpha_2: 'hm',  alpha_3: '')
Country.create(name: 'Holy See (Vatican City State)', alpha_2: 'va', alpha_3: 'vat')
Country.create(name: 'Honduras', alpha_2: 'hn', alpha_3: 'hnd')
Country.create(name: 'Hong Kong', alpha_2: 'hk', alpha_3: 'hkg')
Country.create(name: 'Hungary', alpha_2: 'hu', alpha_3: 'hun')
Country.create(name: 'Iceland', alpha_2: 'is', alpha_3: 'isl')
Country.create(name: 'India', alpha_2: 'in', alpha_3: 'ind')
Country.create(name: 'Indonesia', alpha_2: 'id', alpha_3: 'idn')
Country.create(name: 'Iran, Islamic Republic of', alpha_2: 'ir', alpha_3: 'irn')
Country.create(name: 'Iraq', alpha_2: 'iq', alpha_3: 'irq')
Country.create(name: 'Ireland', alpha_2: 'ie', alpha_3: 'irl')
Country.create(name: 'Isle of Man', alpha_2: 'im', alpha_3: 'imn')
Country.create(name: 'Israel', alpha_2: 'il', alpha_3: 'isr')
Country.create(name: 'Italy', alpha_2: 'it', alpha_3: 'ita')
Country.create(name: 'Jamaica', alpha_2: 'jm', alpha_3: 'jam')
Country.create(name: 'Japan', alpha_2: 'jp', alpha_3: 'jpn')
Country.create(name: 'Jersey', alpha_2: 'je', alpha_3: 'jey')
Country.create(name: 'Jordan', alpha_2: 'jo', alpha_3: 'jor')
Country.create(name: 'Kazakhstan', alpha_2: 'kz', alpha_3: 'kaz')
Country.create(name: 'Kenya', alpha_2: 'ke', alpha_3: 'ken')
Country.create(name: 'Kiribati', alpha_2: 'ki', alpha_3: 'kir')
Country.create(name: "Korea, Democratic People's Republic of", alpha_2: 'kp', alpha_3: 'prk')
Country.create(name: 'Korea, Republic of', alpha_2: 'kr', alpha_3: 'kor')
Country.create(name: 'Kuwait', alpha_2: 'kw', alpha_3: 'kwt')
Country.create(name: 'Kyrgyzstan', alpha_2: 'kg', alpha_3: 'kgz')
Country.create(name: "Lao People's Democratic Republic", alpha_2: 'la', alpha_3: 'lao')
Country.create(name: 'Latvia', alpha_2: 'lv', alpha_3: 'lva')
Country.create(name: 'Lebanon', alpha_2: 'lb', alpha_3: 'lbn')
Country.create(name: 'Lesotho', alpha_2: 'ls', alpha_3: 'lso')
Country.create(name: 'Liberia', alpha_2: 'lr', alpha_3: 'lbr')
Country.create(name: 'Libyan Arab Jamahiriya', alpha_2: 'ly', alpha_3: 'lby')
Country.create(name: 'Liechtenstein', alpha_2: 'li', alpha_3: 'lie')
Country.create(name: 'Lithuania', alpha_2: 'lt', alpha_3: 'ltu')
Country.create(name: 'Luxembourg', alpha_2: 'lu', alpha_3: 'lux')
Country.create(name: 'Macao', alpha_2: 'mo', alpha_3: 'mac')
Country.create(name: 'Macedonia, The former Yugoslav Republic of', alpha_2: 'mk', alpha_3: 'mkd')
Country.create(name: 'Madagascar', alpha_2: 'mg', alpha_3: 'mdg')
Country.create(name: 'Malawi', alpha_2: 'mw', alpha_3: 'mwi')
Country.create(name: 'Malaysia', alpha_2: 'my', alpha_3: 'mys')
Country.create(name: 'Maldives', alpha_2: 'mv', alpha_3: 'mdv')
Country.create(name: 'Mali', alpha_2: 'ml', alpha_3: 'mli')
Country.create(name: 'Malta', alpha_2: 'mt', alpha_3: 'mlt')
Country.create(name: 'Marshall Islands', alpha_2: 'mh', alpha_3: 'mhl')
Country.create(name: 'Martinique', alpha_2: 'mq', alpha_3: 'mtq')
Country.create(name: 'Mauritania', alpha_2: 'mr', alpha_3: 'mrt')
Country.create(name: 'Mauritius', alpha_2: 'mu', alpha_3: 'mus')
Country.create(name: 'Mayotte', alpha_2: 'yt', alpha_3: 'myt')
Country.create(name: 'Mexico', alpha_2: 'mx', alpha_3: 'mex')
Country.create(name: 'Micronesia, Federated States of', alpha_2: 'fm', alpha_3: 'fsm')
Country.create(name: 'Moldova, Republic of', alpha_2: 'md', alpha_3: 'mda')
Country.create(name: 'Monaco', alpha_2: 'mc', alpha_3: 'mco')
Country.create(name: 'Mongolia', alpha_2: 'mn', alpha_3: 'mng')
Country.create(name: 'Montenegro', alpha_2: 'me', alpha_3: 'mne')
Country.create(name: 'Montserrat', alpha_2: 'ms', alpha_3: 'msr')
Country.create(name: 'Morocco', alpha_2: 'ma', alpha_3: 'mar')
Country.create(name: 'Mozambique', alpha_2: 'mz', alpha_3: 'moz')
Country.create(name: 'Myanmar', alpha_2: 'mm', alpha_3: 'mmr')
Country.create(name: 'Namibia', alpha_2: 'na', alpha_3: 'nam')
Country.create(name: 'Nauru', alpha_2: 'nr', alpha_3: 'nru')
Country.create(name: 'Nepal', alpha_2: 'np', alpha_3: 'npl')
Country.create(name: 'Netherlands', alpha_2: 'nl', alpha_3: 'nld')
Country.create(name: 'New Caledonia', alpha_2: 'nc', alpha_3: 'ncl')
Country.create(name: 'New Zealand', alpha_2: 'nz', alpha_3: 'nzl')
Country.create(name: 'Nicaragua', alpha_2: 'ni', alpha_3: 'nic')
Country.create(name: 'Niger', alpha_2: 'ne', alpha_3: 'ner')
Country.create(name: 'Nigeria', alpha_2: 'ng', alpha_3: 'nga')
Country.create(name: 'Niue', alpha_2: 'nu', alpha_3: 'niu')
Country.create(name: 'Norfolk Island', alpha_2: 'nf', alpha_3: 'nfk')
Country.create(name: 'Northern Mariana Islands', alpha_2: 'mp', alpha_3: 'mnp')
Country.create(name: 'Norway', alpha_2: 'no', alpha_3: 'nor')
Country.create(name: 'Oman', alpha_2: 'om', alpha_3: 'omn')
Country.create(name: 'Pakistan', alpha_2: 'pk', alpha_3: 'pak')
Country.create(name: 'Palau', alpha_2: 'pw', alpha_3: 'plw')
Country.create(name: 'Palestinian Territory, Occupied', alpha_2: 'ps', alpha_3: 'pse')
Country.create(name: 'Panama', alpha_2: 'pa', alpha_3: 'pan')
Country.create(name: 'Papua New Guinea', alpha_2: 'pg', alpha_3: 'png')
Country.create(name: 'Paraguay', alpha_2: 'py', alpha_3: 'pry')
Country.create(name: 'Peru', alpha_2: 'pe', alpha_3: 'per')
Country.create(name: 'Philippines', alpha_2: 'ph', alpha_3: 'phl')
Country.create(name: 'Pitcairn', alpha_2: 'pn', alpha_3: 'pcn')
Country.create(name: 'Poland', alpha_2: 'pl', alpha_3: 'pol')
Country.create(name: 'Portugal', alpha_2: 'pt', alpha_3: 'prt')
Country.create(name: 'Puerto Rico', alpha_2: 'pr', alpha_3: 'pri')
Country.create(name: 'Qatar', alpha_2: 'qa', alpha_3: 'qat')
Country.create(name: 'Reunion', alpha_2: 're', alpha_3: 'reu')
Country.create(name: 'Romania', alpha_2: 'ro', alpha_3: 'rou')
Country.create(name: 'Russian Federation', alpha_2: 'ru', alpha_3: 'rus')
Country.create(name: 'Rwanda', alpha_2: 'rw', alpha_3: 'rwa')
Country.create(name: 'Saint Barthelemy', alpha_2: 'bl', alpha_3: 'blm')
Country.create(name: 'Saint Helena, Ascension and Tristan Da Cunha', alpha_2: 'sh', alpha_3: 'shn')
Country.create(name: 'Saint Kitts and Nevis', alpha_2: 'kn', alpha_3: 'kna')
Country.create(name: 'Saint Lucia', alpha_2: 'lc', alpha_3: 'lca')
Country.create(name: 'Saint Martin (French Part)', alpha_2: 'mf', alpha_3: 'maf')
Country.create(name: 'Saint Pierre and Miquelon', alpha_2: 'pm', alpha_3: 'spm')
Country.create(name: 'Saint Vincent and The Grenadines', alpha_2: 'vc', alpha_3: 'vct')
Country.create(name: 'Samoa', alpha_2: 'ws', alpha_3: 'wsm')
Country.create(name: 'San Marino', alpha_2: 'sm', alpha_3: 'smr')
Country.create(name: 'Sao Tome and Principe', alpha_2: 'st', alpha_3: 'stp')
Country.create(name: 'Saudi Arabia', alpha_2: 'sa', alpha_3: 'sau')
Country.create(name: 'Senegal', alpha_2: 'sn', alpha_3: 'sen')
Country.create(name: 'Serbia', alpha_2: 'rs', alpha_3: 'srb')
Country.create(name: 'Seychelles', alpha_2: 'sc', alpha_3: 'syc')
Country.create(name: 'Sierra Leone', alpha_2: 'sl', alpha_3: 'sle')
Country.create(name: 'Singapore', alpha_2: 'sg', alpha_3: 'sgp')
Country.create(name: 'Sint Maarten (Dutch Part)', alpha_2: 'sx', alpha_3: 'sxm')
Country.create(name: 'Slovakia', alpha_2: 'sk', alpha_3: 'svk')
Country.create(name: 'Slovenia', alpha_2: 'si', alpha_3: 'svn')
Country.create(name: 'Solomon Islands', alpha_2: 'sb', alpha_3: 'slb')
Country.create(name: 'Somalia', alpha_2: 'so', alpha_3: 'som')
Country.create(name: 'South Africa', alpha_2: 'za', alpha_3: 'zaf')
Country.create(name: 'South Georgia and The South Sandwich Islands', alpha_2: 'gs',  alpha_3: '')
Country.create(name: 'South Sudan', alpha_2: 'ss', alpha_3: 'ssd')
Country.create(name: 'Spain', alpha_2: 'es', alpha_3: 'esp')
Country.create(name: 'Sri Lanka', alpha_2: 'lk', alpha_3: 'lka')
Country.create(name: 'Sudan', alpha_2: 'sd', alpha_3: 'sdn')
Country.create(name: 'Suriname', alpha_2: 'sr', alpha_3: 'sur')
Country.create(name: 'Svalbard and Jan Mayen', alpha_2: 'sj', alpha_3: 'sjm')
Country.create(name: 'Swaziland', alpha_2: 'sz', alpha_3: 'swz')
Country.create(name: 'Sweden', alpha_2: 'se', alpha_3: 'swe')
Country.create(name: 'Switzerland', alpha_2: 'ch', alpha_3: 'che')
Country.create(name: 'Syrian Arab Republic', alpha_2: 'sy', alpha_3: 'syr')
Country.create(name: 'Taiwan, Province of China', alpha_2: 'tw', alpha_3: '')
Country.create(name: 'Tajikistan', alpha_2: 'tj', alpha_3: 'tjk')
Country.create(name: 'Tanzania, United Republic of', alpha_2: 'tz', alpha_3: 'tza')
Country.create(name: 'Thailand', alpha_2: 'th', alpha_3: 'tha')
Country.create(name: 'Timor-Leste', alpha_2: 'tl', alpha_3: 'tls')
Country.create(name: 'Togo', alpha_2: 'tg', alpha_3: 'tgo')
Country.create(name: 'Tokelau', alpha_2: 'tk', alpha_3: 'tkl')
Country.create(name: 'Tonga', alpha_2: 'to', alpha_3: 'ton')
Country.create(name: 'Trinidad and Tobago', alpha_2: 'tt', alpha_3: 'tto')
Country.create(name: 'Tunisia', alpha_2: 'tn', alpha_3: 'tun')
Country.create(name: 'Turkey', alpha_2: 'tr', alpha_3: 'tur')
Country.create(name: 'Turkmenistan', alpha_2: 'tm', alpha_3: 'tkm')
Country.create(name: 'Turks and Caicos Islands', alpha_2: 'tc', alpha_3: 'tca')
Country.create(name: 'Tuvalu', alpha_2: 'tv', alpha_3: 'tuv')
Country.create(name: 'Uganda', alpha_2: 'ug', alpha_3: 'uga')
Country.create(name: 'Ukraine', alpha_2: 'ua', alpha_3: 'ukr')
Country.create(name: 'United Arab Emirates', alpha_2: 'ae', alpha_3: 'are')
Country.create(name: 'United Kingdom', alpha_2: 'gb', alpha_3: 'gbr')
Country.create(name: 'United States', alpha_2: 'us', alpha_3: 'usa')
Country.create(name: 'United States Minor Outlying Islands', alpha_2: 'um', alpha_3: '')
Country.create(name: 'Uruguay', alpha_2: 'uy', alpha_3: 'ury')
Country.create(name: 'Uzbekistan', alpha_2: 'uz', alpha_3: 'uzb')
Country.create(name: 'Vanuatu', alpha_2: 'vu', alpha_3: 'vut')
Country.create(name: 'Venezuela, Bolivarian Republic of', alpha_2: 've', alpha_3: 'ven')
Country.create(name: 'Viet Nam', alpha_2: 'vn', alpha_3: 'vnm')
Country.create(name: 'Virgin Islands, British', alpha_2: 'vg', alpha_3: 'vgb')
Country.create(name: 'Virgin Islands, U.S.', alpha_2: 'vi', alpha_3: 'vir')
Country.create(name: 'Wallis and Futuna', alpha_2: 'wf', alpha_3: 'wlf')
Country.create(name: 'Western Sahara', alpha_2: 'eh', alpha_3: 'esh')
Country.create(name: 'Yemen', alpha_2: 'ye', alpha_3: 'yem')
Country.create(name: 'Zambia', alpha_2: 'zm', alpha_3: 'zmb')
Country.create(name: 'Zimbabwe', alpha_2: 'zw', alpha_3: 'zwe');
