
INSERT INTO `specialties` (`name`) VALUES
    ('Allergy'),
    ('Anesthesia'),
    ('Associate Degree and Diploma Nurses'),
    ('Athletic Trainer'),
    ('Baccalaureate Prepared Nurses'),
    ('Bioengineering/Biomedical Engineering'),
    ('Cardiac Surgery'),
    ('Cardiology'),
    ('Chiropractics '),
    ('Counseling'),
    ('Dental Assistant'),
    ('Dental Hygienist'),
    ('Dental Lab Technician'),
    ('Dentist'),
    ('Dermatology'),
    ('Doctoral Prepared Nurses'),
    ('Ear / Nose / Throat'),
    ('Emergency Medicine'),
    ('Endocrinology'),
    ('Environmental Health'),
    ('Epidemology'),
    ('Family Medicine'),
    ('Gastroeterology'),
    ('General Surgery'),
    ('Health Education'),
    ('Healthcare Administration'),
    ('Hematology'),
    ('Infectious Disease'),
    ('Internal Medicine'),
    ('International Health'),
    ('Lab Medicine'),
    ('Laboratory Technician'),
    ('Masters Prepared Nurses'),
    ('Mental Health'),
    ('Midwife'),
    ('Nephrology'),
    ('Neurology'),
    ('Non-Medical'),
    ('Nutrition'),
    ('Obstetrics / Gynecology'),
    ('Occupational Therapy'),
    ('Oncology'),
    ('Ophthalmology'),
    ('Optometry'),
    ('Oral Surgeon'),
    ('Orthopaedic Surgery'),
    ('Osteopathic'),
    ('Other (Medical)'),
    ('Other (Surgical)'),
    ('Paramedic/Aviation Medicine'),
    ('Pediatrics'),
    ('Pharmacy'),
    ('Physical Medicine and Rehabilitation'),
    ('Physical Therapy'),
    ('Physician Assistant'),
    ('Plastic Surgery'),
    ('Public Health'),
    ('Pulmonology'),
    ('Radiology'),
    ('Radiology Technician'),
    ('Research'),
    ('Rheumatology'),
    ('Social Services'),
    ('Speech Pathology'),
    ('Water & Sanitation');
    
    
